server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://101.132.152.2:3306/front?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sn442348
  jpa:
    database: MYSQL
    hibernate:
     ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎